name: linter

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      # Installer uniquement si PR interne (les forks n'ont pas accès aux secrets)
      - name: Install PHP & Node Deps (with Flux auth)
        # if tu veux garder la protection fork :
        #  if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        env:
          COMPOSER_HTTP_BASIC_COMPOSER_FLUXUI_DEV_USERNAME: ${{ secrets.FLUX_USERNAME }}
          COMPOSER_HTTP_BASIC_COMPOSER_FLUXUI_DEV_PASSWORD: ${{ secrets.FLUX_LICENSE_KEY }}
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci

      - name: Run Pint
        run: vendor/bin/pint --test
